import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Generated files carry a first-line header. `link` only overwrites a file
 * that carries it; anything else at that path belongs to the user.
 */
const MARK = "generated by agentic from .agentic/ — do not edit";

export function headerFor(file: string): string {
  const hint = "run `agentic link <platform>` to regenerate";
  return file.endsWith(".toml")
    ? `# ${MARK}; ${hint}`
    : `<!-- ${MARK}; ${hint} -->`;
}

export function isGenerated(absPath: string): boolean {
  try {
    if (fs.lstatSync(absPath).isSymbolicLink()) return false;
    const fd = fs.openSync(absPath, "r");
    try {
      const buf = Buffer.alloc(256);
      const n = fs.readSync(fd, buf, 0, 256, 0);
      return buf.subarray(0, n).toString("utf-8").includes(MARK);
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return false;
  }
}

export type WriteResult = "written" | "unchanged" | "conflict";

/**
 * Write a generated file. Refuses (returns "conflict") when a real,
 * non-generated file already sits at the path.
 */
export function writeGenerated(absPath: string, body: string): WriteResult {
  const content = headerFor(absPath) + "\n" + body;
  if (fs.existsSync(absPath) || isSymlink(absPath)) {
    if (isSymlink(absPath)) {
      // A symlink here is a v0.2 leftover only if it points into .agentic/;
      // the caller decides that. Here we just refuse to clobber blindly.
      return "conflict";
    }
    if (!isGenerated(absPath)) return "conflict";
    if (fs.readFileSync(absPath, "utf-8") === content) return "unchanged";
  }
  fs.mkdirSync(path.dirname(absPath), { recursive: true });
  fs.writeFileSync(absPath, content);
  return "written";
}

/** Remove a generated file. No-op when absent or not generated. */
export function removeGenerated(absPath: string): boolean {
  if (!isGenerated(absPath)) return false;
  fs.unlinkSync(absPath);
  return true;
}

function isSymlink(p: string): boolean {
  try {
    return fs.lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}
