import * as fs from "node:fs";
import * as path from "node:path";
import { PLATFORMS, getAgenticDir, platformPaths, type PlatformId } from "./platforms.js";
import { safeLink, isLinkInto, isDangling, isSymlink } from "./symlink.js";
import { writeGenerated, removeGenerated, isGenerated, headerFor } from "./generated.js";
import { addPlatformEntries, removePlatformEntries } from "./gitignore.js";
import {
  readMcpJson,
  writeMcpJson,
  mcpJsonToToml,
  mergeMcpServers,
  mcpJsonToAntigravity,
  agentMdToToml,
} from "./translate.js";
import { ensureLock, writeLock } from "./lock.js";

export interface LinkReport {
  platform: PlatformId;
  added: string[];
  removed: string[];
  updated: string[];
  unchanged: number;
  conflicts: string[];
}

interface Sources {
  hasProject: boolean;
  /** name → absolute path, from rules/ then project/ */
  rules: Map<string, string>;
  /** relative-to-.agentic path for each rules file, in load order */
  rulesRel: string[];
  skills: Map<string, string>;
  agents: Map<string, string>;
  conflicts: string[];
}

function collectSources(agenticDir: string): Sources {
  const s: Sources = {
    hasProject: fs.existsSync(path.join(agenticDir, "PROJECT.md")),
    rules: new Map(),
    rulesRel: [],
    skills: new Map(),
    agents: new Map(),
    conflicts: [],
  };

  for (const sub of ["rules", "project"]) {
    const dir = path.join(agenticDir, sub);
    for (const name of listFiles(dir, ".md")) {
      if (s.rules.has(name)) {
        s.conflicts.push(
          `${sub}/${name} collides with rules/${name} — rename one (both load into the same rules directory)`
        );
        continue;
      }
      s.rules.set(name, path.join(dir, name));
      s.rulesRel.push(`${sub}/${name}`);
    }
  }

  const skillsDir = path.join(agenticDir, "skills");
  for (const name of listDirs(skillsDir)) {
    if (fs.existsSync(path.join(skillsDir, name, "SKILL.md"))) {
      s.skills.set(name, path.join(skillsDir, name));
    }
  }

  const agentsDir = path.join(agenticDir, "agents");
  for (const name of listFiles(agentsDir, ".md")) {
    s.agents.set(name, path.join(agentsDir, name));
  }

  return s;
}

/** Body of the generated root rules file (without the header line). */
export function renderRoot(
  cwd: string,
  platform: PlatformId,
  mode: "import" | "concat" = PLATFORMS[platform].rulesRootMode
): string {
  const m = PLATFORMS[platform];
  const agenticDir = getAgenticDir(cwd);
  const s = collectSources(agenticDir);

  const parts = [".agentic/RULES.md"];
  if (s.hasProject) parts.push(".agentic/PROJECT.md");
  if (m.rulesDir === null || mode === "concat") {
    for (const rel of s.rulesRel) parts.push(`.agentic/${rel}`);
  }

  if (mode === "import") {
    return parts.map((p) => `${m.importPrefix}${p}`).join("\n") + "\n";
  }

  const sections: string[] = [];
  for (const p of parts) {
    const abs = path.join(cwd, p);
    const body = fs.existsSync(abs) ? fs.readFileSync(abs, "utf-8").trim() : "";
    sections.push(`<!-- ${p} -->\n${body}`);
  }
  return sections.join("\n\n") + "\n";
}

function emptyReport(platform: PlatformId): LinkReport {
  return { platform, added: [], removed: [], updated: [], unchanged: 0, conflicts: [] };
}

/**
 * Derive one platform's config from .agentic/. Idempotent.
 * With `apply: false`, report what would change without touching disk.
 */
export function linkPlatform(
  cwd: string,
  platform: PlatformId,
  opts: { apply: boolean } = { apply: true }
): LinkReport {
  const m = PLATFORMS[platform];
  const agenticDir = getAgenticDir(cwd);
  const apply = opts.apply;
  const report = emptyReport(platform);

  const s = collectSources(agenticDir);
  report.conflicts.push(...s.conflicts);

  // Sources that a symlink must be able to reach.
  const mcpSrc = path.join(agenticDir, ".mcp.json");
  if (!fs.existsSync(mcpSrc) && apply) writeMcpJson(mcpSrc, { mcpServers: {} });

  // --- Root rules file (always generated) ---
  const rootAbs = path.join(cwd, m.rulesRoot);
  if (isSymlink(rootAbs)) {
    if (isLinkInto(rootAbs, agenticDir)) {
      if (apply) fs.unlinkSync(rootAbs);
      report.removed.push(`${m.rulesRoot} (whole-file symlink from v0.2)`);
    } else {
      report.conflicts.push(`${m.rulesRoot} is a symlink to outside .agentic/`);
    }
  }
  if (!isSymlink(rootAbs)) {
    const body = renderRoot(cwd, platform);
    const expected = headerFor(rootAbs) + "\n" + body;
    const exists = fs.existsSync(rootAbs);
    if (exists && !isGenerated(rootAbs)) {
      report.conflicts.push(
        `${m.rulesRoot} exists and is not generated by agentic — move its content into .agentic/PROJECT.md and remove it`
      );
    } else if (exists && fs.readFileSync(rootAbs, "utf-8") === expected) {
      report.unchanged++;
    } else {
      if (apply) writeGenerated(rootAbs, body);
      (exists ? report.updated : report.added).push(m.rulesRoot);
    }
  }

  // --- rules/ + project/ → per-file links (only where the platform auto-loads a dir) ---
  if (m.rulesDir) {
    reconcileLinks(path.join(cwd, m.rulesDir), s.rules, agenticDir, m.rulesDir, report, apply);
  }

  // --- skills/ → per-directory links ---
  reconcileLinks(path.join(cwd, m.skillsDir), s.skills, agenticDir, m.skillsDir, report, apply);

  // --- agents/ ---
  const agentsAbs = path.join(cwd, m.agentsDir);
  switch (m.agentsMode) {
    case "link":
      reconcileLinks(agentsAbs, s.agents, agenticDir, m.agentsDir, report, apply);
      break;
    case "link-dir":
      reconcileLinkDirs(agentsAbs, s.agents, agenticDir, m.agentsDir, report, apply);
      break;
    case "translate":
      reconcileGeneratedToml(agentsAbs, s.agents, m.agentsDir, report, apply, (src) =>
        agentMdToToml(fs.readFileSync(src, "utf-8"))
      );
      break;
  }

  // --- MCP ---
  linkMcp(cwd, platform, report, apply);

  // --- gitignore + lock ---
  if (apply) {
    addPlatformEntries(cwd, platform);
    // Always rewrite: this also drops platform ids readLock no longer knows.
    const lock = ensureLock(cwd);
    if (!lock.platforms.includes(platform)) lock.platforms.push(platform);
    writeLock(cwd, lock);
  }

  return report;
}

/** Re-derive only the MCP part for a platform (used by `mcp add/remove`). */
export function linkMcp(
  cwd: string,
  platform: PlatformId,
  report: LinkReport = emptyReport(platform),
  apply = true
): LinkReport {
  const m = PLATFORMS[platform];
  const agenticDir = getAgenticDir(cwd);
  const src = path.join(agenticDir, ".mcp.json");
  const target = path.join(cwd, m.mcp.target);
  const config = readMcpJson(src);

  switch (m.mcp.type) {
    case "symlink": {
      if (isSymlink(target) && !isLinkInto(target, agenticDir)) {
        report.conflicts.push(`${m.mcp.target} is a symlink to outside .agentic/`);
      } else if (!isSymlink(target) && fs.existsSync(target)) {
        report.conflicts.push(
          `${m.mcp.target} exists and is not a symlink — merge it into .agentic/.mcp.json and remove it`
        );
      } else if (isSymlink(target) && !isDangling(target)) {
        report.unchanged++;
      } else {
        if (apply) safeLink(src, target);
        report.added.push(m.mcp.target);
      }
      break;
    }
    case "merge": {
      const dialect = m.mcp.dialect === "antigravity" ? mcpJsonToAntigravity(config) : config;
      const before = fs.existsSync(target) ? fs.readFileSync(target, "utf-8") : null;
      const after =
        JSON.stringify({ ...(before ? JSON.parse(before) : {}), mcpServers: dialect.mcpServers }, null, 2) + "\n";
      if (before === after) {
        report.unchanged++;
      } else {
        if (apply) mergeMcpServers(target, dialect);
        (before === null ? report.added : report.updated).push(`${m.mcp.target}#mcpServers`);
      }
      break;
    }
    case "translate": {
      const body = mcpJsonToToml(config);
      const expected = headerFor(target) + "\n" + body;
      const exists = fs.existsSync(target);
      if (exists && !isGenerated(target)) {
        report.conflicts.push(`${m.mcp.target} exists and is not generated by agentic`);
      } else if (exists && fs.readFileSync(target, "utf-8") === expected) {
        report.unchanged++;
      } else {
        if (apply) writeGenerated(target, body);
        (exists ? report.updated : report.added).push(m.mcp.target);
      }
      break;
    }
  }
  return report;
}

export interface UnlinkReport {
  platform: PlatformId;
  removed: string[];
  kept: string[];
}

/**
 * Remove everything `link` created for a platform. Nothing else. A path
 * that another linked platform also uses (Antigravity and Codex share
 * AGENTS.md and .agents/skills) is left alone.
 */
export function unlinkPlatform(cwd: string, platform: PlatformId): UnlinkReport {
  const m = PLATFORMS[platform];
  const agenticDir = getAgenticDir(cwd);
  const report: UnlinkReport = { platform, removed: [], kept: [] };

  const lock = ensureLock(cwd);
  const shared = new Set(
    lock.platforms.filter((p) => p !== platform && p in PLATFORMS).flatMap(platformPaths)
  );
  const isShared = (rel: string) => {
    if (!shared.has(rel)) return false;
    report.kept.push(`${rel} (still used by another linked platform)`);
    return true;
  };

  const rootAbs = path.join(cwd, m.rulesRoot);
  if (!isShared(m.rulesRoot)) {
    if (isLinkInto(rootAbs, agenticDir)) {
      fs.unlinkSync(rootAbs);
      report.removed.push(m.rulesRoot);
    } else if (removeGenerated(rootAbs)) {
      report.removed.push(m.rulesRoot);
    } else if (fs.existsSync(rootAbs)) {
      report.kept.push(`${m.rulesRoot} (not generated by agentic)`);
    }
  }

  const linkDirs = [m.rulesDir, m.skillsDir, m.agentsMode === "link" ? m.agentsDir : null];
  for (const rel of linkDirs) {
    if (!rel || isShared(rel)) continue;
    const abs = path.join(cwd, rel);
    if (isLinkInto(abs, agenticDir)) {
      fs.unlinkSync(abs);
      report.removed.push(`${rel} (whole-directory symlink from v0.2)`);
      continue;
    }
    if (!fs.existsSync(abs)) continue;
    for (const name of fs.readdirSync(abs)) {
      const p = path.join(abs, name);
      if (isLinkInto(p, agenticDir)) {
        fs.unlinkSync(p);
        report.removed.push(`${rel}/${name}`);
      } else {
        report.kept.push(`${rel}/${name}`);
      }
    }
    removeIfEmpty(abs);
  }

  if (m.agentsMode === "link-dir" && !isShared(m.agentsDir)) {
    const abs = path.join(cwd, m.agentsDir);
    if (fs.existsSync(abs)) {
      for (const name of fs.readdirSync(abs)) {
        const inner = path.join(abs, name, "agent.md");
        if (isLinkInto(inner, agenticDir)) {
          fs.unlinkSync(inner);
          removeIfEmpty(path.join(abs, name));
          report.removed.push(`${m.agentsDir}/${name}/agent.md`);
        } else {
          report.kept.push(`${m.agentsDir}/${name}`);
        }
      }
      removeIfEmpty(abs);
    }
  }

  if (m.agentsMode === "translate" && !isShared(m.agentsDir)) {
    const abs = path.join(cwd, m.agentsDir);
    if (fs.existsSync(abs)) {
      for (const name of fs.readdirSync(abs)) {
        const p = path.join(abs, name);
        if (name.endsWith(".toml") && removeGenerated(p)) report.removed.push(`${m.agentsDir}/${name}`);
        else report.kept.push(`${m.agentsDir}/${name}`);
      }
      removeIfEmpty(abs);
    }
  }

  const mcpTarget = path.join(cwd, m.mcp.target);
  if (!isShared(m.mcp.target)) {
    switch (m.mcp.type) {
      case "symlink":
        if (isLinkInto(mcpTarget, agenticDir)) {
          fs.unlinkSync(mcpTarget);
          report.removed.push(m.mcp.target);
        }
        break;
      case "merge":
        if (fs.existsSync(mcpTarget)) {
          const settings = JSON.parse(fs.readFileSync(mcpTarget, "utf-8"));
          if ("mcpServers" in settings) {
            delete settings.mcpServers;
            if (Object.keys(settings).length === 0) fs.unlinkSync(mcpTarget);
            else fs.writeFileSync(mcpTarget, JSON.stringify(settings, null, 2) + "\n");
            report.removed.push(`${m.mcp.target}#mcpServers`);
          }
        }
        break;
      case "translate":
        if (removeGenerated(mcpTarget)) report.removed.push(m.mcp.target);
        break;
    }
  }

  removePlatformEntries(cwd, platform);
  removeIfEmpty(path.join(cwd, m.configDir));
  removeIfEmpty(path.join(cwd, ".agents"));

  if (lock.platforms.includes(platform)) {
    lock.platforms = lock.platforms.filter((p) => p !== platform);
    writeLock(cwd, lock);
  }

  return report;
}

// --- reconciliation ---

/**
 * Make `dirAbs` hold exactly one symlink per desired entry, pointing into
 * .agentic/. Rules:
 *   1. add a link for each source entry that has none
 *   2. remove a symlink into .agentic/ that dangles or is no longer desired
 *   3. never touch an entry that is not a symlink into .agentic/
 *   4. a desired name taken by a real file/dir is a conflict — report, skip
 */
function reconcileLinks(
  dirAbs: string,
  desired: Map<string, string>,
  agenticDir: string,
  label: string,
  report: LinkReport,
  apply: boolean
): void {
  if (!prepareDir(dirAbs, desired.size, agenticDir, label, report, apply)) return;

  if (fs.existsSync(dirAbs)) {
    for (const name of fs.readdirSync(dirAbs)) {
      const p = path.join(dirAbs, name);
      if (!isLinkInto(p, agenticDir)) continue;
      if (!desired.has(name) || isDangling(p)) {
        if (apply) fs.unlinkSync(p);
        report.removed.push(`${label}/${name}`);
      }
    }
  }

  for (const [name, target] of desired) {
    placeLink(path.join(dirAbs, name), target, agenticDir, `${label}/${name}`, report, apply);
  }
}

/**
 * Same contract as reconcileLinks, but each source `<name>.md` becomes
 * `<dir>/<name>/agent.md` (Antigravity's custom-agent layout).
 */
function reconcileLinkDirs(
  dirAbs: string,
  desired: Map<string, string>,
  agenticDir: string,
  label: string,
  report: LinkReport,
  apply: boolean
): void {
  const want = new Map<string, string>();
  for (const [name, src] of desired) want.set(name.replace(/\.md$/, ""), src);

  if (!prepareDir(dirAbs, want.size, agenticDir, label, report, apply)) return;

  if (fs.existsSync(dirAbs)) {
    for (const name of fs.readdirSync(dirAbs)) {
      const inner = path.join(dirAbs, name, "agent.md");
      if (!isLinkInto(inner, agenticDir)) continue;
      if (!want.has(name) || isDangling(inner)) {
        if (apply) {
          fs.unlinkSync(inner);
          removeIfEmpty(path.join(dirAbs, name));
        }
        report.removed.push(`${label}/${name}/agent.md`);
      }
    }
  }

  for (const [name, target] of want) {
    const sub = path.join(dirAbs, name);
    if (fs.existsSync(sub) && !fs.statSync(sub).isDirectory()) {
      report.conflicts.push(`${label}/${name} is a real file — rename it or the .agentic/ entry`);
      continue;
    }
    if (!fs.existsSync(sub) && apply) fs.mkdirSync(sub, { recursive: true });
    placeLink(path.join(sub, "agent.md"), target, agenticDir, `${label}/${name}/agent.md`, report, apply);
  }
}

/** Handle a v0.2 whole-directory symlink and make sure the directory exists. */
function prepareDir(
  dirAbs: string,
  wanted: number,
  agenticDir: string,
  label: string,
  report: LinkReport,
  apply: boolean
): boolean {
  if (isSymlink(dirAbs)) {
    if (isLinkInto(dirAbs, agenticDir)) {
      if (apply) fs.unlinkSync(dirAbs);
      report.removed.push(`${label} (whole-directory symlink from v0.2)`);
    } else {
      report.conflicts.push(`${label} is a symlink to outside .agentic/`);
      return false;
    }
  }
  const exists = fs.existsSync(dirAbs) && !isSymlink(dirAbs);
  if (exists && !fs.statSync(dirAbs).isDirectory()) {
    report.conflicts.push(`${label} exists and is not a directory`);
    return false;
  }
  if (!exists) {
    if (wanted === 0) return false;
    if (apply) fs.mkdirSync(dirAbs, { recursive: true });
  }
  return true;
}

/** Create/retarget one symlink, or report why not. */
function placeLink(
  p: string,
  target: string,
  agenticDir: string,
  label: string,
  report: LinkReport,
  apply: boolean
): void {
  if (isSymlink(p)) {
    if (!isLinkInto(p, agenticDir)) {
      report.conflicts.push(`${label} is a symlink to outside .agentic/`);
      return;
    }
    if (isDangling(p)) {
      if (apply) safeLink(target, p);
      report.added.push(label);
      return;
    }
    const relTarget = path.relative(path.dirname(p), target);
    if (fs.readlinkSync(p) === relTarget) {
      report.unchanged++;
    } else {
      if (apply) safeLink(target, p);
      report.updated.push(label);
    }
  } else if (fs.existsSync(p)) {
    report.conflicts.push(
      `${label} is a real ${fs.statSync(p).isDirectory() ? "directory" : "file"} — rename it or the .agentic/ entry`
    );
  } else {
    if (apply) safeLink(target, p);
    report.added.push(label);
  }
}

/** Same contract as reconcileLinks, for platforms that need a translated file per source. */
function reconcileGeneratedToml(
  dirAbs: string,
  desired: Map<string, string>,
  label: string,
  report: LinkReport,
  apply: boolean,
  translate: (srcAbs: string) => string
): void {
  const want = new Map<string, string>();
  for (const [name, src] of desired) want.set(name.replace(/\.md$/, ".toml"), src);

  if (fs.existsSync(dirAbs)) {
    for (const name of fs.readdirSync(dirAbs)) {
      const p = path.join(dirAbs, name);
      if (!name.endsWith(".toml") || !isGenerated(p)) continue;
      if (!want.has(name)) {
        if (apply) fs.unlinkSync(p);
        report.removed.push(`${label}/${name}`);
      }
    }
  } else if (want.size === 0) {
    return;
  }

  for (const [name, src] of want) {
    const p = path.join(dirAbs, name);
    const body = translate(src);
    const expected = headerFor(p) + "\n" + body;
    const exists = fs.existsSync(p);
    if (exists && !isGenerated(p)) {
      report.conflicts.push(`${label}/${name} exists and is not generated by agentic`);
    } else if (exists && fs.readFileSync(p, "utf-8") === expected) {
      report.unchanged++;
    } else {
      if (apply) writeGenerated(p, body);
      (exists ? report.updated : report.added).push(`${label}/${name}`);
    }
  }
}

// --- fs helpers ---

function listFiles(dir: string, ext: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith(ext))
    .map((d) => d.name)
    .sort();
}

function listDirs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

export function removeIfEmpty(dir: string): void {
  try {
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // absent — fine
  }
}
