// End-to-end tests against dist/cli.js. Run with `npm test`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CLI = path.join(__dirname, "..", "dist", "cli.js");

// --- helpers ---

function cli(cwd, ...args) {
  const r = spawnSync("node", [CLI, ...args], { cwd, encoding: "utf-8" });
  return { status: r.status, out: r.stdout + r.stderr };
}

function ok(cwd, ...args) {
  const r = cli(cwd, ...args);
  assert.equal(r.status, 0, `expected exit 0 for \`${args.join(" ")}\`:\n${r.out}`);
  return r.out;
}

function fail(cwd, ...args) {
  const r = cli(cwd, ...args);
  assert.notEqual(r.status, 0, `expected non-zero exit for \`${args.join(" ")}\`:\n${r.out}`);
  return r.out;
}

function git(cwd, ...args) {
  const r = spawnSync("git", ["-c", "user.name=t", "-c", "user.email=t@t", ...args], {
    cwd,
    encoding: "utf-8",
  });
  assert.equal(r.status, 0, `git ${args.join(" ")} failed:\n${r.stdout}${r.stderr}`);
  return r.stdout.trim();
}

function tmp(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `agentic-${name}-`));
}

function write(base, rel, content) {
  const p = path.join(base, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

function read(base, rel) {
  return fs.readFileSync(path.join(base, rel), "utf-8");
}

function exists(base, rel) {
  try {
    fs.lstatSync(path.join(base, rel));
    return true;
  } catch {
    return false;
  }
}

function isLink(base, rel) {
  return exists(base, rel) && fs.lstatSync(path.join(base, rel)).isSymbolicLink();
}

function lock(project) {
  return JSON.parse(read(project, ".agentic/agentic.lock"));
}

/** Write a fixture harness. `v` selects content so tests can diff versions. */
function makeHarness(dir, v = 1) {
  // reset content but keep a .git dir if the fixture is a repo
  if (fs.existsSync(dir)) {
    for (const name of fs.readdirSync(dir)) {
      if (name !== ".git") fs.rmSync(path.join(dir, name), { recursive: true, force: true });
    }
  }
  write(dir, "harness.json", JSON.stringify({ name: "fixture", version: `${v}.0.0`, protocol: "2.0.0" }));
  write(dir, "rules/COMMON.md", `# Team rules v${v}\n\nRead .agentic/references/workflow.md.\n`);
  write(dir, "references/workflow.md", `# Workflow v${v}\n`);
  write(dir, "rules/PROJECT.md", "# Project (seed)\n");
  write(dir, "skills/commit/SKILL.md", `---\nname: commit\ndescription: commit v${v}\n---\n# commit\n`);
  if (v >= 2) write(dir, "skills/review/SKILL.md", "---\nname: review\ndescription: review\n---\n# review\n");
  if (v === 1) write(dir, "agents/reviewer.md", "---\nname: reviewer\ndescription: reviews\n---\nReview carefully.\n");
  write(
    dir,
    "mcps.json",
    JSON.stringify(
      {
        mcpServers: {
          browser: { command: "npx", args: ["@browsermcp/mcp@latest"] },
          jira: { type: "http", url: "https://mcp.example.com/mcp" },
          ...(v === 1 ? { lsp: { command: "npx", args: ["lsmcp"], env: { TOKEN: "${LSP_TOKEN}" } } } : {}),
        },
      },
      null,
      2
    )
  );
  return dir;
}

function freshProject(name) {
  const project = tmp(name);
  git(project, "init", "-q", "-b", "main");
  write(project, "README.md", "# app\n");
  return project;
}

// --- tests ---

test("install + link claude derives a tracked, per-entry layout", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");

  const out = ok(project, "install", harness);
  assert.match(out, /Installed fixture@1\.0\.0/);
  assert.equal(read(project, ".agentic/rules/COMMON.md"), "# Team rules v1\n\nRead .agentic/references/workflow.md.\n");
  assert.equal(read(project, ".agentic/rules/PROJECT.md"), "# Project (seed)\n");
  assert.ok(!exists(project, ".agentic/project"), "no project/ in the shape");

  const l = lock(project);
  assert.equal(l.protocol, "2.0.0");
  assert.equal(l.harness.name, "fixture");
  assert.deepEqual(Object.keys(l.files).sort(), [
    "agents/reviewer.md",
    "references/workflow.md",
    "rules/COMMON.md",
    "skills/commit/SKILL.md",
  ]);
  assert.deepEqual(Object.keys(l.mcpServers).sort(), ["browser", "jira", "lsp"]);
  assert.ok(!("rules/PROJECT.md" in l.files), "seeds are never in the lock");

  ok(project, "link", "claude");
  assert.equal(
    read(project, "CLAUDE.md").split("\n").slice(1).join("\n"),
    "@.agentic/rules/COMMON.md\n@.agentic/rules/PROJECT.md\n"
  );
  assert.match(read(project, "CLAUDE.md").split("\n")[0], /generated by agentic/);
  assert.ok(!exists(project, ".claude/rules"), "rules load through the root file; no per-file rule links");
  assert.ok(isLink(project, ".claude/skills/commit"));
  assert.ok(isLink(project, ".claude/agents/reviewer.md"));
  assert.ok(isLink(project, ".mcp.json"));
  assert.equal(fs.readlinkSync(path.join(project, ".claude/skills/commit")), "../../.agentic/skills/commit");
  assert.equal(read(project, ".claude/skills/commit/SKILL.md"), read(project, ".agentic/skills/commit/SKILL.md"));

  const ignore = read(project, ".gitignore");
  assert.match(ignore, /\.claude\/settings\.local\.json/);
  assert.match(ignore, /\.claude\/worktrees\//);
  assert.doesNotMatch(ignore, /CLAUDE\.md/);
  assert.doesNotMatch(ignore, /\.claude\/skills/);
  assert.deepEqual(lock(project).platforms, ["claude"]);

  const st = ok(project, "status");
  assert.match(st, /Protocol: 2\.0\.0/);
  assert.match(st, /rules\/\s+2 \(1 harness, 1 project\)/);
  ok(project, "link", "claude"); // idempotent
});

test("a git worktree carries the whole harness", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "claude");
  git(project, "add", "-A");
  git(project, "commit", "-qm", "harness");

  // symlinks are committed as symlinks
  const modes = git(project, "ls-files", "-s").split("\n").filter((l) => l.startsWith("120000"));
  assert.ok(modes.some((l) => l.endsWith("CLAUDE.md")) === false, "CLAUDE.md is a real generated file");
  assert.ok(modes.some((l) => l.endsWith(".claude/skills/commit")));
  assert.ok(modes.some((l) => l.endsWith(".mcp.json")));

  const wt = path.join(tmp("wt"), "feature");
  git(project, "worktree", "add", "-q", wt, "-b", "feature");

  assert.ok(exists(wt, "CLAUDE.md"));
  assert.match(read(wt, "CLAUDE.md"), /@\.agentic\/rules\/COMMON\.md/);
  assert.equal(read(wt, ".claude/skills/commit/SKILL.md"), read(project, ".agentic/skills/commit/SKILL.md"));
  assert.equal(read(wt, ".agentic/rules/COMMON.md"), read(project, ".agentic/rules/COMMON.md"));
  assert.match(read(wt, ".mcp.json"), /browser/);
  ok(wt, "status");
});

test("project-specific skills coexist with harness and project cross-platform skills", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "claude");

  write(project, ".claude/skills/claude-only/SKILL.md", "---\nname: claude-only\n---\n");
  write(project, ".agentic/skills/my-skill/SKILL.md", "---\nname: my-skill\n---\n");

  const out = ok(project, "link", "claude");
  assert.match(out, /\+ \.claude\/skills\/my-skill/);
  assert.ok(isLink(project, ".claude/skills/my-skill"));
  assert.ok(!isLink(project, ".claude/skills/claude-only"), "real dir untouched");
  ok(project, "status");

  // a real dir in the way of a source entry is a conflict, not a clobber
  write(project, ".claude/skills/commit-clash/SKILL.md", "");
  write(project, ".agentic/skills/commit-clash/SKILL.md", "");
  const r = cli(project, "link", "claude");
  assert.equal(r.status, 1);
  assert.match(r.out, /commit-clash is a real directory/);
  assert.equal(read(project, ".claude/skills/commit-clash/SKILL.md"), "");
});

test("update applies the four-case table and re-links", () => {
  const hdir = tmp("harness");
  makeHarness(hdir, 1);
  const project = freshProject("proj");
  ok(project, "install", hdir);
  ok(project, "link", "claude");

  // hand-edit a harness file, add project content, then bump the harness
  write(project, ".agentic/references/workflow.md", "# Workflow v1 — local tweak\n");
  write(project, ".agentic/skills/my-skill/SKILL.md", "---\nname: my-skill\n---\n");
  write(project, ".agentic/references/notes.md", "keep me\n");
  write(project, ".agentic/rules/PROJECT.md", "# Project — mine\n");
  makeHarness(hdir, 2); // COMMON changes, review added, reviewer agent + lsp mcp removed

  const r = cli(project, "update");
  assert.equal(r.status, 1, r.out);
  assert.match(r.out, /references\/workflow\.md: modified locally/);
  assert.equal(read(project, ".agentic/rules/COMMON.md"), "# Team rules v2\n\nRead .agentic/references/workflow.md.\n", "overwrite");
  assert.equal(read(project, ".agentic/references/workflow.md"), "# Workflow v1 — local tweak\n", "conflict skipped");
  assert.ok(exists(project, ".agentic/skills/review/SKILL.md"), "add");
  assert.ok(!exists(project, ".agentic/agents/reviewer.md"), "delete");
  assert.ok(exists(project, ".agentic/skills/my-skill/SKILL.md"), "project skill untouched");
  assert.equal(read(project, ".agentic/references/notes.md"), "keep me\n", "project file inside a harness dir untouched");
  assert.equal(read(project, ".agentic/rules/PROJECT.md"), "# Project — mine\n", "seed untouched even when edited");

  const mcp = JSON.parse(read(project, ".agentic/.mcp.json"));
  assert.ok(!("lsp" in mcp.mcpServers), "harness mcp key removed");
  assert.ok("browser" in mcp.mcpServers);

  // re-link happened
  assert.ok(isLink(project, ".claude/skills/review"));
  assert.ok(!exists(project, ".claude/agents/reviewer.md"), "dangling agent link pruned");

  const l = lock(project);
  assert.equal(l.harness.version, "2.0.0");
  assert.ok(!("agents/reviewer.md" in l.files));
  assert.ok("skills/review/SKILL.md" in l.files);
  assert.ok("references/workflow.md" in l.files, "conflicted path stays in the lock so it keeps surfacing");

  // status reports the drift
  const s = cli(project, "status");
  assert.equal(s.status, 1);
  assert.match(s.out, /references\/workflow\.md: modified locally/);

  // second update: same conflict, nothing else
  const r2 = cli(project, "update");
  assert.equal(r2.status, 1);
  assert.match(r2.out, /1 conflict skipped/);

  // --force takes upstream
  ok(project, "update", "--force");
  assert.equal(read(project, ".agentic/references/workflow.md"), "# Workflow v2\n");
  ok(project, "status");
});

test("update: project file at a newly harness-owned path is a conflict", () => {
  const hdir = tmp("harness");
  makeHarness(hdir, 1);
  const project = freshProject("proj");
  ok(project, "install", hdir);
  write(project, ".agentic/skills/review/SKILL.md", "mine\n"); // project made this first
  makeHarness(hdir, 2); // harness now ships review

  const r = cli(project, "update");
  assert.equal(r.status, 1);
  assert.match(r.out, /skills\/review\/SKILL\.md: project file at a path the harness now owns/);
  assert.equal(read(project, ".agentic/skills/review/SKILL.md"), "mine\n");
  assert.ok(!("skills/review/SKILL.md" in lock(project).files));
});

test("update with an explicit path pulls from a local checkout", () => {
  const h1 = makeHarness(tmp("h1"), 1);
  const h2 = makeHarness(tmp("h2"), 2);
  const project = freshProject("proj");
  ok(project, "install", h1);
  const out = ok(project, "update", h2);
  assert.match(out, /1\.0\.0.*→ fixture@2\.0\.0/);
  assert.equal(lock(project).harness.source, h2);
});

test("install from a git URL records the commit; update re-clones from the lock", () => {
  const hdir = makeHarness(tmp("harness"), 1);
  git(hdir, "init", "-q", "-b", "main");
  git(hdir, "add", "-A");
  git(hdir, "commit", "-qm", "v1");
  const sha1 = git(hdir, "rev-parse", "HEAD");

  const project = freshProject("proj");
  ok(project, "install", `file://${hdir}#main`);
  let l = lock(project);
  assert.equal(l.harness.source, `file://${hdir}`);
  assert.equal(l.harness.ref, "main");
  assert.equal(l.harness.commit, sha1);

  makeHarness(hdir, 2);
  git(hdir, "add", "-A");
  git(hdir, "commit", "-qm", "v2");
  const sha2 = git(hdir, "rev-parse", "HEAD");

  ok(project, "update");
  l = lock(project);
  assert.equal(l.harness.commit, sha2);
  assert.equal(l.harness.version, "2.0.0");

  // a commit sha as ref goes through the full-clone fallback
  const p2 = freshProject("proj2");
  ok(p2, "install", `file://${hdir}#${sha1}`);
  assert.equal(lock(p2).harness.version, "1.0.0");
});

test("install refuses to overwrite differing local content, adopts identical content", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "init");
  // init wrote its own rules/COMMON.md stub → conflict
  const out = fail(project, "install", harness);
  assert.match(out, /rules\/COMMON\.md/);
  assert.match(out, /Nothing was written/);
  assert.ok(!exists(project, ".agentic/skills/commit"));

  // identical content is adopted (the v0.2 migration path)
  fs.copyFileSync(path.join(harness, "rules/COMMON.md"), path.join(project, ".agentic/rules/COMMON.md"));
  fs.cpSync(path.join(harness, "skills/commit"), path.join(project, ".agentic/skills/commit"), { recursive: true });
  const out2 = ok(project, "install", harness);
  assert.match(out2, /2 already present, adopted/);
});

test("v0.2 whole-directory symlinks migrate to per-entry links", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  // replicate a v0.2 install: content in .agentic/, whole-dir links, ignored derived files
  fs.cpSync(harness, path.join(project, ".agentic"), { recursive: true });
  fs.unlinkSync(path.join(project, ".agentic/harness.json"));
  fs.renameSync(path.join(project, ".agentic/mcps.json"), path.join(project, ".agentic/.mcp.json"));
  fs.renameSync(path.join(project, ".agentic/rules/COMMON.md"), path.join(project, ".agentic/RULES.md"));
  fs.renameSync(path.join(project, ".agentic/rules/PROJECT.md"), path.join(project, ".agentic/PROJECT.md"));
  fs.symlinkSync(".agentic/RULES.md", path.join(project, "CLAUDE.md"));
  fs.symlinkSync(".agentic/.mcp.json", path.join(project, ".mcp.json"));
  fs.mkdirSync(path.join(project, ".claude"));
  fs.symlinkSync("../.agentic/skills", path.join(project, ".claude/skills"));
  fs.symlinkSync("../.agentic/agents", path.join(project, ".claude/agents"));
  write(
    project,
    ".gitignore",
    "node_modules/\n\n# Claude Code (derived from .agentic/)\n/CLAUDE.md\n/.mcp.json\n.claude/skills\n.claude/agents\n.claude/settings.local.json\n"
  );

  // no lock + the old paths ⇒ protocol 1.0: install migrates first, then adopts everything as identical
  const inst = ok(project, "install", harness);
  assert.match(inst, /Migrated \.agentic\/ from protocol 1\.0\.0 to 2\.0\.0/);
  assert.match(inst, /RULES\.md → rules\/COMMON\.md/);
  assert.match(inst, /PROJECT\.md → rules\/PROJECT\.md/);
  assert.match(inst, /4 harness files \(7 already present, adopted\)/, "4 files + 3 MCP keys, all identical");
  assert.equal(lock(project).protocol, "2.0.0");
  const out = ok(project, "link", "claude");
  assert.match(out, /CLAUDE\.md \(whole-file symlink from v0\.2\)/);
  assert.match(out, /\.claude\/skills \(whole-directory symlink from v0\.2\)/);
  assert.ok(!isLink(project, "CLAUDE.md"));
  assert.ok(!isLink(project, ".claude/skills"));
  assert.ok(isLink(project, ".claude/skills/commit"));
  assert.ok(isLink(project, ".claude/agents/reviewer.md"));
  const ignore = read(project, ".gitignore");
  assert.doesNotMatch(ignore, /\/CLAUDE\.md/);
  assert.match(ignore, /node_modules\//);
  assert.match(ignore, /\.claude\/worktrees\//);
});

test("uninstall removes harness content, keeps project content and modified files, prunes links", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "claude");
  write(project, ".agentic/skills/my-skill/SKILL.md", "---\nname: my-skill\n---\n");
  write(project, ".agentic/references/workflow.md", "edited\n");
  ok(project, "link", "claude");

  const out = ok(project, "uninstall");
  assert.match(out, /references\/workflow\.md \(modified locally\)/);
  assert.ok(!exists(project, ".agentic/rules/COMMON.md"));
  assert.ok(!exists(project, ".agentic/skills/commit"));
  assert.ok(!exists(project, ".agentic/agents/reviewer.md"));
  assert.ok(exists(project, ".agentic/rules") && exists(project, ".agentic/agents"), "standard top-level dirs stay");
  assert.ok(exists(project, ".agentic/references/workflow.md"), "modified file kept");
  assert.ok(exists(project, ".agentic/skills/my-skill/SKILL.md"));
  assert.ok(exists(project, ".agentic/rules/PROJECT.md"));
  assert.ok(!exists(project, ".claude/skills/commit"), "link pruned");
  assert.ok(isLink(project, ".claude/skills/my-skill"));
  assert.ok(!exists(project, ".claude/agents/reviewer.md"));

  const l = lock(project);
  assert.equal(l.harness, null);
  assert.deepEqual(l.files, {});
  assert.deepEqual(l.platforms, ["claude"]);
  assert.deepEqual(JSON.parse(read(project, ".agentic/.mcp.json")).mcpServers, {});

  // re-install: the kept edit now collides with the harness file
  assert.match(fail(project, "install", harness), /references\/workflow\.md/);
  fs.unlinkSync(path.join(project, ".agentic/references/workflow.md"));
  ok(project, "install", harness);
  assert.ok(isLink(project, ".claude/skills/commit"), "re-install re-links recorded platforms");
});

test("unlink removes only what link created", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "claude");
  write(project, ".claude/skills/claude-only/SKILL.md", "");
  write(project, ".claude/settings.json", "{}\n");

  const out = ok(project, "unlink", "claude");
  assert.match(out, /kept/);
  assert.ok(!exists(project, "CLAUDE.md"));
  assert.ok(!exists(project, ".mcp.json"));
  assert.ok(!exists(project, ".claude/skills/commit"));
  assert.ok(!exists(project, ".claude/rules"));
  assert.ok(!exists(project, ".claude/agents"));
  assert.ok(exists(project, ".claude/skills/claude-only/SKILL.md"));
  assert.ok(exists(project, ".claude/settings.json"));
  assert.doesNotMatch(read(project, ".gitignore"), /Claude Code/);
  assert.deepEqual(lock(project).platforms, []);
  ok(project, "link", "claude");
});

test("mcp add refuses literal secrets and marks ownership", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "antigravity");

  const out = fail(project, "mcp", "add", "gh", "npx", "mcp-github", "--env", "GITHUB_TOKEN=ghp_abc");
  assert.match(out, /must be \$\{NAME\} references/);

  ok(project, "mcp", "add", "gh", "npx", "mcp-github", "--env", "GITHUB_TOKEN=${GITHUB_TOKEN}");
  const list = ok(project, "mcp", "list");
  assert.match(list, /gh: npx mcp-github  \[project\]/);
  assert.match(list, /browser: .*\[harness\]/);
  const agy = JSON.parse(read(project, ".agents/mcp_config.json"));
  assert.ok("gh" in agy.mcpServers, "propagated to linked platform");

  const warn = cli(project, "mcp", "remove", "browser");
  assert.equal(warn.status, 0);
  assert.match(warn.out, /harness-owned/);

  // a harness with a literal secret is rejected at install
  const bad = makeHarness(tmp("bad"));
  write(bad, "mcps.json", JSON.stringify({ mcpServers: { x: { command: "x", env: { K: "literal" } } } }));
  const p2 = freshProject("proj2");
  assert.match(fail(p2, "install", bad), /x\.env\.K/);
});

test("antigravity and codex link, sharing AGENTS.md and .agents/skills", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  write(project, ".agentic/rules/PROJECT.md", "# Project (seed)\n\nNotes for this project.\n");

  ok(project, "link", "antigravity");
  const agents = read(project, "AGENTS.md");
  assert.match(agents.split("\n")[0], /^<!-- generated by agentic/);
  assert.match(agents, /<!-- \.agentic\/rules\/COMMON\.md -->\n# Team rules v1/, "COMMON inlined");
  assert.match(agents, /<!-- \.agentic\/rules\/PROJECT\.md -->\n# Project \(seed\)\n\nNotes for this project\./, "PROJECT inlined");
  assert.ok(agents.indexOf("# Team rules v1") < agents.indexOf("# Project (seed)"), "COMMON before PROJECT, so the project overrides");
  assert.ok(isLink(project, ".agents/skills/commit"));
  assert.ok(isLink(project, ".agents/agents/reviewer/agent.md"), "antigravity custom-agent layout");
  assert.equal(read(project, ".agents/agents/reviewer/agent.md"), read(project, ".agentic/agents/reviewer.md"));
  const mcp = JSON.parse(read(project, ".agents/mcp_config.json"));
  assert.ok("browser" in mcp.mcpServers);
  assert.deepEqual(mcp.mcpServers.jira, { serverUrl: "https://mcp.example.com/mcp" }, "remote servers use serverUrl");
  assert.equal(JSON.parse(read(project, ".agentic/.mcp.json")).mcpServers.jira.url, "https://mcp.example.com/mcp", "source untouched");
  assert.ok(!exists(project, ".gitignore"), "nothing to ignore → no .gitignore written at all");
  assert.ok(!exists(project, "GEMINI.md"));
  assert.ok(!exists(project, ".gemini"));

  const out = ok(project, "link", "codex");
  assert.match(out, /\(\d+ unchanged\)/);
  assert.doesNotMatch(out, /\+ AGENTS\.md/, "AGENTS.md is identical for both platforms");
  assert.doesNotMatch(out, /\+ \.agents\/skills\/commit/);
  const toml = read(project, ".codex/agents/reviewer.toml");
  assert.match(toml.split("\n")[0], /^# generated by agentic/);
  assert.match(toml, /name = "reviewer"/);
  assert.match(read(project, ".codex/config.toml"), /\[mcp_servers\.browser\]/);
  assert.match(read(project, ".codex/config.toml"), /\[mcp_servers\.jira\]/, "http server kept");
  assert.match(read(project, ".codex/config.toml"), /url = "https:\/\/mcp\.example\.com\/mcp"/, "http server keeps its url");
  assert.deepEqual(lock(project).platforms, ["antigravity", "codex"]);
  ok(project, "status");

  // unlinking one platform keeps what the other still needs
  const un = ok(project, "unlink", "codex");
  assert.match(un, /AGENTS\.md \(still used by another linked platform\)/);
  assert.ok(exists(project, "AGENTS.md"));
  assert.ok(isLink(project, ".agents/skills/commit"));
  assert.ok(!exists(project, ".codex"));
  ok(project, "status");

  ok(project, "unlink", "antigravity");
  assert.ok(!exists(project, "AGENTS.md"));
  assert.ok(!exists(project, ".agents"));
  assert.deepEqual(lock(project).platforms, []);
});

test("a lock that names a removed platform is tolerated", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  const l = lock(project);
  l.platforms = ["gemini", "claude"];
  write(project, ".agentic/agentic.lock", JSON.stringify(l, null, 2) + "\n");
  const out = ok(project, "link", "claude");
  assert.match(out, /unknown platform "gemini"/);
  assert.deepEqual(lock(project).platforms, ["claude"]);
});

test("root file that is not generated is a conflict", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  write(project, "CLAUDE.md", "# hand-written\n");
  ok(project, "install", harness);
  const r = cli(project, "link", "claude");
  assert.equal(r.status, 1);
  assert.match(r.out, /CLAUDE\.md exists and is not generated/);
  assert.equal(read(project, "CLAUDE.md"), "# hand-written\n");
  assert.ok(isLink(project, ".claude/skills/commit"), "the rest still links");
});

test("eject flattens to standalone files", () => {
  const harness = makeHarness(tmp("harness"));
  const project = freshProject("proj");
  ok(project, "install", harness);
  ok(project, "link", "claude");
  ok(project, "link", "codex");
  ok(project, "link", "antigravity");

  ok(project, "eject");
  assert.ok(!isLink(project, ".agents/agents/reviewer/agent.md"));
  assert.match(read(project, ".agents/agents/reviewer/agent.md"), /name: reviewer/);
  assert.ok(!exists(project, ".agentic"));
  assert.ok(!isLink(project, "CLAUDE.md"));
  assert.match(read(project, "CLAUDE.md"), /# Team rules v1/);
  assert.match(read(project, "CLAUDE.md"), /# Project \(seed\)/, "eject inlines rules/PROJECT.md too");
  assert.doesNotMatch(read(project, "CLAUDE.md"), /generated by agentic/);
  assert.ok(!isLink(project, ".claude/skills/commit"));
  assert.equal(read(project, ".claude/skills/commit/SKILL.md").includes("commit"), true);
  assert.ok(!isLink(project, ".mcp.json"));
  assert.doesNotMatch(read(project, ".codex/config.toml"), /generated by/);
  assert.doesNotMatch(read(project, ".gitignore"), /derived from \.agentic/);
});

test("init creates a harness-less .agentic that links", () => {
  const project = freshProject("proj");
  ok(project, "init");
  fail(project, "init");
  assert.ok(exists(project, ".agentic/rules/COMMON.md") && exists(project, ".agentic/rules/PROJECT.md"));
  assert.ok(!exists(project, ".agentic/RULES.md") && !exists(project, ".agentic/project"), "no protocol-1.0 paths");
  assert.equal(lock(project).protocol, "2.0.0");
  write(project, ".agentic/skills/mine/SKILL.md", "---\nname: mine\n---\n");
  ok(project, "link", "claude");
  assert.ok(isLink(project, ".claude/skills/mine"));
  assert.equal(
    read(project, "CLAUDE.md").split("\n").slice(1).join("\n"),
    "@.agentic/rules/COMMON.md\n@.agentic/rules/PROJECT.md\n"
  );
  assert.equal(lock(project).harness, null);
  const s = ok(project, "status");
  assert.match(s, /Harness: \(none\)/);
  fail(project, "update");
  fail(project, "uninstall");
});

test("rules/ holds only COMMON.md and PROJECT.md; the v1.0 shape is a conflict with a hint", () => {
  const project = freshProject("proj");
  ok(project, "init");

  write(project, ".agentic/rules/testing.md", "# Testing\n");
  let r = cli(project, "link", "claude");
  assert.equal(r.status, 1);
  assert.match(r.out, /rules\/testing\.md is not loaded/);
  assert.doesNotMatch(read(project, "CLAUDE.md"), /testing\.md/);
  assert.ok(!exists(project, ".claude/rules"), "never linked per file");
  fs.unlinkSync(path.join(project, ".agentic/rules/testing.md"));

  write(project, ".agentic/RULES.md", "# old\n");
  write(project, ".agentic/project/domain.md", "# old\n");
  r = cli(project, "link", "claude");
  assert.equal(r.status, 1);
  assert.match(r.out, /\.agentic\/RULES\.md is the protocol-1\.0 shape/);
  assert.match(r.out, /\.agentic\/project is the protocol-1\.0 shape/);
  assert.match(r.out, /rules\/COMMON\.md/, "the hint names the new path");
  assert.equal(cli(project, "status").status, 1, "status gates on it too");
  fs.unlinkSync(path.join(project, ".agentic/RULES.md"));
  fs.rmSync(path.join(project, ".agentic/project"), { recursive: true });
  ok(project, "link", "claude");
  ok(project, "status");

  // a harness on another protocol, or with extra rules files, is rejected before anything is written
  const old = makeHarness(tmp("old"));
  write(old, "harness.json", JSON.stringify({ name: "fixture", version: "1.0.0" })); // no protocol ⇒ 1.0.0
  const p2 = freshProject("proj2");
  const older = fail(p2, "install", old);
  assert.match(older, /protocol 1\.0\.0 is not compatible with protocol 2\.0\.0/);
  assert.match(older, /migrate the harness/);
  // same MAJOR, higher MINOR: the harness uses something this build does not know
  write(old, "harness.json", JSON.stringify({ name: "fixture", version: "1.0.0", protocol: "2.1.0" }));
  assert.match(fail(p2, "install", old), /upgrade agentic/);
  write(old, "harness.json", JSON.stringify({ name: "fixture", version: "1.0.0", protocol: "3.0.0" }));
  assert.match(fail(p2, "install", old), /upgrade agentic/);
  // same MAJOR, lower-or-equal MINOR and any PATCH: accepted (its own project — p2 must stay empty)
  write(old, "harness.json", JSON.stringify({ name: "fixture", version: "1.0.0", protocol: "2.0.9" }));
  const p3 = freshProject("proj3");
  ok(p3, "install", old);
  assert.equal(lock(p3).protocol, "2.0.0", "the lock records the tool's protocol, not the harness's");
  const extra = makeHarness(tmp("extra"));
  write(extra, "rules/style.md", "# style\n");
  assert.match(fail(p2, "install", extra), /rules\/style\.md: rules\/ holds only/);
  assert.ok(!exists(p2, ".agentic"), "nothing written");
});

test("migrate: a protocol-1.0 project is refused by link/status/unlink and moved by migrate", () => {
  const project = freshProject("proj");
  ok(project, "init");
  ok(project, "link", "claude");
  // rewind to the shape v1.0.0 left: root rules files, topic files, per-file links, no protocol in the lock
  fs.renameSync(path.join(project, ".agentic/rules/COMMON.md"), path.join(project, ".agentic/RULES.md"));
  fs.unlinkSync(path.join(project, ".agentic/rules/PROJECT.md"));
  write(project, ".agentic/PROJECT.md", "# My project\n");
  write(project, ".agentic/rules/style.md", "# Style\n\nTabs.\n");
  write(project, ".agentic/project/domain.md", "# Domain\n\nOrders.\n");
  fs.mkdirSync(path.join(project, ".claude/rules"), { recursive: true }); // link created no .claude/: init has no skills
  fs.symlinkSync("../../.agentic/rules/style.md", path.join(project, ".claude/rules/style.md"));
  write(project, ".claude/rules/mine.md", "---\npaths:\n  - \"src/**\"\n---\n# mine\n");
  const l = lock(project);
  delete l.protocol;
  write(project, ".agentic/agentic.lock", JSON.stringify(l, null, 2) + "\n");

  for (const args of [["link", "claude"], ["status"], ["unlink", "claude"]]) {
    const r = cli(project, ...args);
    assert.equal(r.status, 1, args.join(" "));
    assert.match(r.out, /on protocol 1\.0\.0; this agentic reads 2\.0\.0/);
    assert.match(r.out, /agentic migrate/);
  }
  assert.ok(exists(project, ".agentic/RULES.md"), "refused, not touched");

  const out = ok(project, "migrate");
  assert.match(out, /Migrated \.agentic\/ from protocol 1\.0\.0 to 2\.0\.0/);
  assert.match(out, /RULES\.md → rules\/COMMON\.md/);
  assert.match(out, /PROJECT\.md → rules\/PROJECT\.md/);
  assert.match(out, /rules\/style\.md folded into rules\/PROJECT\.md as "## style"/);
  assert.match(out, /project\/domain\.md folded into rules\/PROJECT\.md as "## domain"/);
  assert.match(out, /\.claude\/rules\/style\.md removed/);
  assert.ok(!exists(project, ".agentic/RULES.md") && !exists(project, ".agentic/PROJECT.md"));
  assert.ok(!exists(project, ".agentic/rules/style.md") && !exists(project, ".agentic/project"));
  const pr = read(project, ".agentic/rules/PROJECT.md");
  assert.match(pr, /^# My project\n/);
  assert.match(pr, /## style\n<!-- migrated from \.agentic\/rules\/style\.md \(protocol 1 to 2\) -->\n# Style\n\nTabs\./);
  assert.match(pr, /## domain\n<!-- migrated from \.agentic\/project\/domain\.md .*-->\n# Domain\n\nOrders\./);
  assert.ok(!exists(project, ".claude/rules/style.md"));
  assert.match(read(project, ".claude/rules/mine.md"), /# mine/, "a real rules file is the project's");
  assert.equal(lock(project).protocol, "2.0.0");
  assert.equal(
    read(project, "CLAUDE.md").split("\n").slice(1).join("\n"),
    "@.agentic/rules/COMMON.md\n@.agentic/rules/PROJECT.md\n",
    "recorded platforms re-linked"
  );
  ok(project, "status");
  assert.match(ok(project, "migrate"), /Already on protocol 2\.0\.0/);
});

test("update migrates a protocol-1.0 lock first, then reconciles harness-owned files", () => {
  const hdir = tmp("harness");
  makeHarness(hdir, 1);
  const project = freshProject("proj");
  ok(project, "install", hdir);
  ok(project, "link", "claude");
  // rewind: harness-owned RULES.md at the root, lock keyed on it, no protocol
  fs.renameSync(path.join(project, ".agentic/rules/COMMON.md"), path.join(project, ".agentic/RULES.md"));
  const l = lock(project);
  l.files["RULES.md"] = l.files["rules/COMMON.md"];
  delete l.files["rules/COMMON.md"];
  delete l.protocol;
  write(project, ".agentic/agentic.lock", JSON.stringify(l, null, 2) + "\n");

  const out = ok(project, "update");
  assert.match(out, /Migrated \.agentic\/ from protocol 1\.0\.0 to 2\.0\.0/);
  assert.match(out, /RULES\.md is harness-owned/);
  assert.match(out, /added: 1\n\s+rules\/COMMON\.md/);
  assert.match(out, /removed: 1\n\s+RULES\.md/);
  assert.ok(!exists(project, ".agentic/RULES.md"));
  assert.equal(read(project, ".agentic/rules/COMMON.md"), "# Team rules v1\n\nRead .agentic/references/workflow.md.\n");
  const l2 = lock(project);
  assert.equal(l2.protocol, "2.0.0");
  assert.ok("rules/COMMON.md" in l2.files && !("RULES.md" in l2.files));
  ok(project, "status");
});

test("status warns, without failing, when the two rules files pass 200 lines", () => {
  const project = freshProject("proj");
  ok(project, "init");
  ok(project, "link", "claude");
  assert.doesNotMatch(ok(project, "status"), /over 200/);
  write(project, ".agentic/rules/PROJECT.md", "# Project\n" + "- a rule\n".repeat(200));
  const s = cli(project, "status");
  assert.equal(s.status, 0, "size is advice, not drift");
  assert.match(s.out, /over 200/);
});

test("migrate distinguishes a step that found nothing from no step at all", () => {
  const project = freshProject("proj");
  ok(project, "init");
  ok(project, "link", "claude");

  // protocol-1.0 lock, but the files are already in the 2.0.0 shape — what you get
  // when the move was done by hand before migrating.
  const l = lock(project);
  delete l.protocol;
  write(project, ".agentic/agentic.lock", JSON.stringify(l, null, 2) + "\n");
  const out = ok(project, "migrate");
  assert.match(out, /already in the new shape, nothing to move/);
  assert.doesNotMatch(out, /no shape change between them/, "a MAJOR step did run");
  assert.equal(lock(project).protocol, "2.0.0");
  ok(project, "status");
});

test("--version names the protocol; a MINOR-behind lock is restamped, not migrated", () => {
  const project = freshProject("proj");
  ok(project, "init");
  assert.match(ok(project, "--version"), /^\d+\.\d+\.\d+ \(harness protocol 2\.0\.0\)/);

  // a lock one MINOR behind: same shape, so commands work and migrate only restamps
  const l = lock(project);
  l.protocol = "2.0.0";
  write(project, ".agentic/agentic.lock", JSON.stringify({ ...l, protocol: "1.9.0" }, null, 2) + "\n");
  assert.equal(cli(project, "status").status, 1, "a different MAJOR is refused");

  write(project, ".agentic/agentic.lock", JSON.stringify({ ...l, protocol: "2.0.0" }, null, 2) + "\n");
  ok(project, "status");
});
